# Generated by Django 5.2.13 on 2026-04-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
